name: Selenium E2E test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Test
        run: mvn clean test -Denv=local -Dbrowser=chrome


      - name: Upload Extent Reports
        run: |
          mkdir -p report
          cp extent-report.html report/

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TESTNGTOCKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report
