name: Selenium E2E test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run tests with Maven
        run: mvn test -DsuiteXmlFile=testng.xml


      - name: Get ExtentReport history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: List files in target directory  # Vérifier que les rapports existent
        run: |
          ls -R target

      - name: Save ExtentReport to gh-pages directory
        run: |
          mkdir -p gh-pages/extent-report
          cp -r target/extent-report/* gh-pages/extent-report/

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TESTNGTOCKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: gh-pages/extent-report
